### ISSUE TITLE
chown: cannot access '/dev/kvm': No such file or directory

### ISSUE THREAD

**Issue by tch1001** [gabrieleara/dev_environment#7]
I tried running the `kernel` image
```
docker run -it gabrieleara/dev_environment:kernel
```
and received this error,
```
Adding user root to group libvirt
Adding user root to group kvm
chown: cannot access '/dev/kvm': No such file or directory
```
I am on a x86 MacOS

I dug around the `kernel` git branch and found the Dockerfile, which I saw was based on `gabrieleara/dev_environment:cpp`. I have managed to run 
```
docker run -it gabrieleara/dev_environment:cpp 
```
successfully though, and checked that `/dev/kvm` does not exist. I suppose it might something to do with docker image versions?

Any help would be appreciated, and thanks for this awesome resource. :) Thanks in advance!

**Comment by gabrieleara** [comment]
Hello!

I think that I probably forgot to specify that you need to bind the `/dev/kvm` device of your host machine (so a Linux host OS is required) before starting the container (something like `-v /dev/kvm:/dev/kvm`. That might be my fault. I'll check it ASAP.

In general, these images rarely can be started simply by using a `docker run` command with no parameters as you did, please refer to the companion `devcontainer.json` file for a reference of command-line arguments typically required to run these images.

**Comment by tch1001** [comment]
ah thank makes a lot of sense, fixed! thank you for the prompt response!! i tried to  use `devcontainers.json` because it gave me another error... until i mounted the `/dev/kvm` and it works flawlessly! Thanks alot!

**Comment by gabrieleara** [comment]
You're welcome. 😄

I'll see that I fix it so that the kvm device can be optionally not shared and the image still works (albeit without Qemu-KVM support, maybe triggering a warning message).

In the mean time, I can suggest you [this article](https://www.gabrieleara.it/random_notes/20211104_kernel_devel/#configuring-and-building-the-linux-kernel) of mine about how to use this image as developing environment for the Linux kernel in VSCode.
